export const ErrorCodes = {
  // Operator errors
  OPERATOR_NOT_FOUND: "OPERATOR_NOT_FOUND",
  OPERATOR_DISABLED: "OPERATOR_DISABLED",
  OPERATOR_EXEC_FAILED: "OPERATOR_EXEC_FAILED",
  OPERATOR_TIMEOUT: "OPERATOR_TIMEOUT",
  OPERATOR_PATH_MISSING: "OPERATOR_PATH_MISSING",

  // Bundle errors
  BUNDLE_HASH_MISMATCH: "BUNDLE_HASH_MISMATCH",
  BUNDLE_SCHEMA_INVALID: "BUNDLE_SCHEMA_INVALID",
  BUNDLE_INCOMPLETE: "BUNDLE_INCOMPLETE",

  // Approval errors
  APPROVAL_FILE_MISSING: "APPROVAL_FILE_MISSING",
  APPROVAL_NOT_GRANTED: "APPROVAL_NOT_GRANTED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",

  // Pack errors
  PACK_NOT_FOUND: "PACK_NOT_FOUND",
  PACK_MANIFEST_MISSING: "PACK_MANIFEST_MISSING",
  PACK_CHECKS_MISSING: "PACK_CHECKS_MISSING",
  PACK_VALIDATION_FAILED: "PACK_VALIDATION_FAILED",

  // Config errors
  CONFIG_INVALID: "CONFIG_INVALID",
  KPI_TARGETS_MISSING: "KPI_TARGETS_MISSING",

  // Publish errors
  PUBLISH_BLOCKED: "PUBLISH_BLOCKED",
  PUBLISH_UNAPPROVED: "PUBLISH_UNAPPROVED",

  // Metrics errors
  METRICS_CSV_NOT_FOUND: "METRICS_CSV_NOT_FOUND",
  METRICS_CSV_PARSE_ERROR: "METRICS_CSV_PARSE_ERROR",
  METRICS_CSV_EMPTY: "METRICS_CSV_EMPTY",
  METRICS_SNAPSHOT_NOT_FOUND: "METRICS_SNAPSHOT_NOT_FOUND",

  // Experiment errors
  EXPERIMENT_GENERATION_FAILED: "EXPERIMENT_GENERATION_FAILED",

  // Approval integrity
  APPROVAL_HASH_INVALID: "APPROVAL_HASH_INVALID",
  APPROVAL_STALE: "APPROVAL_STALE",

  // Conversion errors
  CONVERSION_CSV_NOT_FOUND: "CONVERSION_CSV_NOT_FOUND",
  CONVERSION_CSV_EMPTY: "CONVERSION_CSV_EMPTY",
  CONVERSION_CONFIG_INVALID: "CONVERSION_CONFIG_INVALID",
  CONVERSION_NO_DATA: "CONVERSION_NO_DATA",

  // Geo priority errors
  GEO_CONFIG_NOT_FOUND: "GEO_CONFIG_NOT_FOUND",
  GEO_ZIP_NOT_FOUND: "GEO_ZIP_NOT_FOUND",
  GEO_TIER_INVALID: "GEO_TIER_INVALID",

  // Efficiency guard errors
  EFFICIENCY_INPUT_INVALID: "EFFICIENCY_INPUT_INVALID",
  EFFICIENCY_ZIP_SUPPRESSED: "EFFICIENCY_ZIP_SUPPRESSED",

  // Profit errors
  PROFIT_NO_CLOSE_RATES: "PROFIT_NO_CLOSE_RATES",

  // Lead quality errors
  LEAD_QUALITY_CONFIG_MISSING: "LEAD_QUALITY_CONFIG_MISSING",
  LEAD_QUALITY_INVALID_SIGNALS: "LEAD_QUALITY_INVALID_SIGNALS",

  // Calibration errors
  OUTCOMES_CSV_NOT_FOUND: "OUTCOMES_CSV_NOT_FOUND",
  OUTCOMES_CSV_EMPTY: "OUTCOMES_CSV_EMPTY",
  OUTCOMES_CSV_INVALID: "OUTCOMES_CSV_INVALID",
  CALIBRATION_LOW_SAMPLE: "CALIBRATION_LOW_SAMPLE",

  // Seasonality errors
  SEASON_INTENT_BLOCKED: "SEASON_INTENT_BLOCKED",

  // Waste hunter errors
  WASTE_CSV_NOT_FOUND: "WASTE_CSV_NOT_FOUND",
  WASTE_CSV_EMPTY: "WASTE_CSV_EMPTY",

  // Conservative mode errors
  CONSERVATIVE_SCALE_BLOCKED: "CONSERVATIVE_SCALE_BLOCKED",
  CONSERVATIVE_PULLBACK: "CONSERVATIVE_PULLBACK",
  CAPACITY_EXCEEDED: "CAPACITY_EXCEEDED",
  TIER2_EXPANSION_BLOCKED: "TIER2_EXPANSION_BLOCKED",
  TIER4_EXPANSION_BLOCKED: "TIER4_EXPANSION_BLOCKED",

  // Flow governor errors
  FLOW_DAILY_CAP_EXCEEDED: "FLOW_DAILY_CAP_EXCEEDED",
  FLOW_INSTALL_CAP_EXCEEDED: "FLOW_INSTALL_CAP_EXCEEDED",
  FLOW_REPAIR_CAP_EXCEEDED: "FLOW_REPAIR_CAP_EXCEEDED",
  FLOW_BACKLOG_OVERLOAD: "FLOW_BACKLOG_OVERLOAD",
  FLOW_UPGRADE_RATIO_LOW: "FLOW_UPGRADE_RATIO_LOW",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
