import type { ToolDefinition } from "../types/index.js";

export const toolDefinitions: ToolDefinition[] = [
  {
    id: "orchestrator.plan.weekly",
    name: "Generate Weekly Plan",
    version: "1.0.0",
    description: "Uses KPI targets to decide which operator intents to run this week",
    category: "planner",
    inputSchema: { type: "object", properties: { weekNumber: { type: "number" } }, required: ["weekNumber"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.operator.run",
    name: "Run Operator Command",
    version: "1.0.0",
    description: "Executes an operator CLI command and captures structured output",
    category: "runner",
    inputSchema: {
      type: "object",
      properties: { operator: { type: "string" }, command: { type: "string" }, args: { type: "array" } },
      required: ["operator", "command"],
    },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.bundle.assemble",
    name: "Assemble Weekly Bundle",
    version: "1.0.0",
    description: "Collects operator packs into a single weekly bundle with deterministic hash",
    category: "assembler",
    inputSchema: { type: "object", properties: { weekNumber: { type: "number" }, intent: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.approvals.scan",
    name: "Scan Approvals",
    version: "1.0.0",
    description: "Scans all operator pack folders for approval.json and aggregates status",
    category: "approvals",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.approvals.proxy",
    name: "Proxy Approve",
    version: "1.0.0",
    description: "Proxies an approval command to a specific operator",
    category: "approvals",
    inputSchema: {
      type: "object",
      properties: { operator: { type: "string" }, packPath: { type: "string" }, itemId: { type: "string" } },
      required: ["operator", "packPath", "itemId"],
    },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.report.weekly",
    name: "Generate Weekly Report",
    version: "1.0.0",
    description: "Produces a master report with KPI snapshot, operator summaries, and next actions",
    category: "report",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.status",
    name: "Show Status",
    version: "1.0.0",
    description: "Shows current KPIs, approvals, and blocked items",
    category: "report",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.bundle.validate",
    name: "Validate Bundle",
    version: "1.0.0",
    description: "Validates a bundle for completeness, schema compliance, and approval status",
    category: "validator",
    inputSchema: { type: "object", properties: { bundlePath: { type: "string" } }, required: ["bundlePath"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.bundle.export",
    name: "Export Bundle",
    version: "1.0.0",
    description: "Exports an approved bundle to a target directory",
    category: "export",
    inputSchema: { type: "object", properties: { bundlePath: { type: "string" }, target: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: true,
    sideEffects: true,
  },
  {
    id: "orchestrator.bundle.import",
    name: "Import Bundle to MBS",
    version: "1.0.0",
    description: "FUTURE: MBS tool for importing orchestration bundles",
    category: "assembler",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    requiresApproval: true,
    sideEffects: true,
  },
  {
    id: "orchestrator.metrics.import",
    name: "Import GSC Metrics",
    version: "1.1.0",
    description: "Parses gsc-pages.csv and gsc-queries.csv from metrics/import/, builds a normalized MetricSnapshot, stores to metrics/snapshots/",
    category: "runner",
    inputSchema: { type: "object", properties: { date: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.metrics.snapshot",
    name: "Load Metric Snapshot",
    version: "1.1.0",
    description: "Loads the latest or a specific date's metric snapshot for KPI overlay",
    category: "report",
    inputSchema: { type: "object", properties: { date: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.experiment.generate",
    name: "Generate Weekly Experiments",
    version: "1.1.0",
    description: "Generates 4 experiments per week (1 SEO + 1 Ads + 1 Call conversion + 1 Form conversion) with hypothesis, variants, stop rules, and rollback plan",
    category: "planner",
    inputSchema: { type: "object", properties: { weekNumber: { type: "number" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.experiment.save",
    name: "Save Experiments to Bundle",
    version: "1.1.0",
    description: "Persists experiment definitions into a bundle's experiments/ directory",
    category: "assembler",
    inputSchema: { type: "object", properties: { bundleDir: { type: "string" }, experiments: { type: "array" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.approvals.integrity",
    name: "Check Approval Integrity",
    version: "1.1.0",
    description: "Validates that pack content has not changed since approval was granted by comparing content hashes",
    category: "validator",
    inputSchema: { type: "object", properties: { packPath: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.conversion.score",
    name: "Score Conversion Value",
    version: "1.2.0",
    description: "Computes weighted conversion value from expected calls and forms using config weights (CALL_CLICK×1.0 + FORM_SUBMIT×0.7)",
    category: "conversion",
    inputSchema: { type: "object", properties: { expectedCalls: { type: "number" }, expectedForms: { type: "number" } }, required: ["expectedCalls", "expectedForms"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.conversion.tiebreaker",
    name: "Conversion Tie-Breaker",
    version: "1.2.0",
    description: "Compares two snapshots within tieBreakerWindowDays to determine which conversion goal (CALL_CLICK or FORM_SUBMIT) is trending stronger",
    category: "conversion",
    inputSchema: { type: "object", properties: { currentDate: { type: "string" }, previousDate: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.conversion.classify",
    name: "Classify Page/Query Intent",
    version: "1.2.0",
    description: "Classifies a page URL or search query as call-first (repair intent), form-first (install intent), or mixed",
    category: "conversion",
    inputSchema: { type: "object", properties: { input: { type: "string" }, type: { type: "string", enum: ["page", "query"] } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.conversion.import_ga4",
    name: "Import GA4 Conversion Events",
    version: "1.2.0",
    description: "Parses GA4 export CSV from metrics/import/ga4-events.csv, maps event names to CALL_CLICK/FORM_SUBMIT, aggregates by page with weighted scoring",
    category: "conversion",
    inputSchema: { type: "object", properties: { csvPath: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.geo.priority",
    name: "Geo Priority Lookup",
    version: "1.4.0",
    description: "Returns tier, weight, and high-priority status for a zip code from geo_priority.json",
    category: "planner",
    inputSchema: { type: "object", properties: { zip: { type: "string" } }, required: ["zip"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.geo.adjustedScore",
    name: "Geo-Adjusted Score",
    version: "1.4.0",
    description: "Computes geoAdjustedScore = baseActionScore × zipWeight for planner intent prioritization",
    category: "planner",
    inputSchema: { type: "object", properties: { baseScore: { type: "number" }, zip: { type: "string" } }, required: ["baseScore", "zip"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.ads.efficiencyGuard",
    name: "Efficiency Guard",
    version: "1.4.0",
    description: "Evaluates zip-level CPL, impression share, and travel distance to generate bid modifier recommendations. Never auto-publishes.",
    category: "conversion",
    inputSchema: { type: "object", properties: { inputs: { type: "array" } }, required: ["inputs"] },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.profit.efficiency",
    name: "Profit Efficiency Score",
    version: "1.4.0",
    description: "Computes weightedLeadValue = (calls×closeRate×ticket) + (forms×closeRate×ticket) and profitEfficiencyScore = value - adSpend",
    category: "conversion",
    inputSchema: { type: "object", properties: { calls: { type: "number" }, forms: { type: "number" }, adSpend: { type: "number" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.leads.qualityScore",
    name: "Lead Quality Scoring",
    version: "1.5.0",
    description: "Scores call and form leads by quality signals (duration, peak hours, field completeness, urgency). Returns QualifiedLeadValue for profit model.",
    category: "leads",
    inputSchema: { type: "object", properties: { leadType: { type: "string" }, signals: { type: "object" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.calibration.run",
    name: "Outcome Calibration",
    version: "1.5.0",
    description: "Imports outcomes.csv, computes observed close rates and avg tickets, writes proposed updates to learned.json (approval-gated).",
    category: "conversion",
    inputSchema: { type: "object", properties: { csvPath: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.seasonality.gate",
    name: "Seasonality Gate",
    version: "1.5.0",
    description: "Blocks out-of-season ad intents. HEATING (Oct-Feb), COOLING (May-Aug), SHOULDER (Mar-Apr, Sep).",
    category: "seasonality",
    inputSchema: { type: "object", properties: { serviceText: { type: "string" }, month: { type: "number" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.ads.wasteHunter",
    name: "Waste Hunter",
    version: "1.5.0",
    description: "Parses Google Ads search terms CSV, identifies high-spend/zero-conversion and irrelevant terms, outputs negative keyword recommendations.",
    category: "waste",
    inputSchema: { type: "object", properties: { csvPath: { type: "string" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: true,
  },
  {
    id: "orchestrator.mode.conservativeGuard",
    name: "Conservative Mode Guard",
    version: "1.6.0",
    description: "Evaluates zips under conservative profit-protection rules. Scale requires ALL checks (CPL < target×0.8, quality, close rate, IS, travel, capacity). Pullback on ANY trigger.",
    category: "conversion",
    inputSchema: { type: "object", properties: { inputs: { type: "array" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.capacity.check",
    name: "Capacity Gate",
    version: "1.6.0",
    description: "Checks technician capacity (backlog hours vs max). Blocks bid increases when capacity exceeded.",
    category: "conversion",
    inputSchema: { type: "object", properties: {} },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.expansion.check",
    name: "Tier Expansion Check",
    version: "1.6.0",
    description: "Gates tier2 and tier4 geo expansion. Tier2 requires tier1 saturation >= 80%, CPL below target, capacity available. Tier4 requires tier1+tier2 profitable + margin >= 1.25x average.",
    category: "planner",
    inputSchema: { type: "object", properties: { intents: { type: "array" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
  {
    id: "orchestrator.flow.governor",
    name: "Lead Flow Governor",
    version: "1.7.0",
    description: "Small-team mode: caps qualified leads/day, install leads/week, repair leads/day, enforces upgrade ratio, triggers backlog-based radius reduction and tier suppression.",
    category: "planner",
    inputSchema: { type: "object", properties: { flowState: { type: "object" } } },
    outputSchema: { type: "object" },
    requiresApproval: false,
    sideEffects: false,
  },
];
